# Generated by Django 3.1.7 on 2021-03-23 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('note', models.IntegerField(blank=True, default=0)),
                ('annee', models.DateField(default=datetime.date.today, verbose_name='date published')),
                ('realisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.realisateur')),
            ],
        ),
    ]
